### PR TITLE
Update abstract text

### PR DESCRIPTION
**Pull request by hsu000001**
Some suggestions from the initial CDI working group and SAS conversations.

### CODE REVIEW

**Comment by skybristol** [comment]
@TWellman and @TrashBirdEcology  - I'm experimenting with methods to work with repos in this org space as part of our lab practice. This is simple, but we're using the repo here to manage aspects of the experimental model catalog @hsu000001 posted some changes to the abstract. If you can take a quick look and post any suggestions or otherwise sign off on the review, that would be great.

**Comment by TrashBirdEcology** [comment]
@skybristol , @hsu000001, @TWellman  [I suggested some edits](https://github.com/usgs-biolab/pymodelcat/pull/2/commits/7716a0fda8b503e4c5280b5ec71713c857f0e8ea) to Leslie's edits. 

I also suggest changing the name of the py code(?) folder, "pymodelcat", as it has the same name as the directory (repository).

**Comment by skybristol** [comment]
> I also suggest changing the name of the py code(?) folder, "pymodelcat", as it has the same name as the directory (repository). As such, will not be approving this.

Wow! You're hard core. This is a common enough practice with Python packages where the name of the package is a logical folder under a directory structure. It can be something different as it's all configurable, but it's a reasonable enough convention that I would just as soon leave well enough alone.

**Comment by TrashBirdEcology** [comment]
Aha....okay well if it makes sense for python then who am i to argue?

**Comment by hsu000001** [comment]
Is it best practice to delete the branch now? I'm a newbie.

**Comment by TWellman** [comment]
Apologies for the delay. I made a few changes to the description. I get inundated by Git repo messaging so I've pushed Git content into different email channels. I failed to check this particular email channel... Oh well!

**Pull request merged**
